version: '3.3'
services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    container_name: mongoDB
    restart: always
    logging:
      options:
        max-size: 1g
    # environment:
    # - MONGO_INITDB_ROOT_USERNAME=mongoadmin
    # - MONGO_INITDB_ROOT_PASSWORD=bdung
